# Redirect API calls to your backend
[[redirects]]
  from = "/api/*"
  to = "https://sweet-adventure-production.up.railway.app/api/:splat"
  status = 200
  force = true

# Redirect all other requests to index.html (for SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://apis.google.com https://js.stripe.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://res.cloudinary.com data: blob:; connect-src 'self' wss://heavenly-demo.netlify.app wss://sweet-adventure-production.up.railway.app; frame-src 'self' https://js.stripe.com; object-src 'none'; frame-ancestors 'none';"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"